### ISSUE TITLE
file-naming problem

### ISSUE THREAD

**Issue by colinleach** [GijsMulders/epos#2]
Gijs,

I just installed epospy 2.0.0 with pip, but the tests and examples don't work as-is: it gives an IOError for all the ones I've tried. The code is looking for files with names like `~/.local/lib/python2.7/site-packages/EPOS/files/*.huber.npz`, but the files on disk are named `*.Huber.npz` (upper case H). I can work around this by renaming the files locally but you might want to fix the repo when you get chance. Unless I'm doing something oddly wrong?

My OS is Linux Mint 19.2, I've not tried other systems (it might work OK on Windows). I'm currently doing a class at LPL with Ilaria and Rachel, so I can ask them about it tomorrow.

Best regards,
Colin

**Comment by GijsMulders** [comment]
Thanks for pointing that out, I think this is an issue with Linux and Mac file systems treating upper case differently. I will fix it in the repository and update it in the next pip version.

In the meantime, renaming the files to lowercase is a good workaround.

**Comment by colinleach** [comment]
Great, thanks.

**Comment by GijsMulders** [comment]
This issue is resolved in epos version 2.0.2

You can update with:
`pip install --upgrade epospy`
